# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Felix Krause
email: website@krausefx.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal website and blog of Felix Krause
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://krausefx.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: KrauseFx
github_username:  KrauseFx

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-twitter-plugin
  - jekyll-seo-tag
permalink: /blog/:title
paginate: 4
paginate_path: "/blog/page:num/"

# Jekyll SEO Tag
author:
  twitter: KrauseFx
defaults:
  - scope:
      path: ""
    values:
      image: /assets/cards/default.jpg
tagline: "Personal website and blog of Felix Krause"
twitter:
  username: KrauseFx
  card: summary_large_image
social:
  name: Felix Krause
  links:
    - https://bsky.app/profile/krausefx.bsky.social
    - https://www.linkedin.com/in/KrauseFx
    - https://github.com/KrauseFx
    - https://keybase.io/KrauseFx



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
